services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.10.5
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command:
      - bash
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --password admin \
          --firstname Vinay \
          --lastname Pandey \
          --role Admin \
          --email admin@example.com || true

  airflow-webserver:
    image: apache/airflow:2.10.5
    entrypoint: []
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WORKERS: "1"
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: "300"
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080
      AIRFLOW__WEBSERVER__COOKIE_SECURE: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ..:/opt/airflow/project
    ports:
      - "8080:8080"
    command:
      - python
      - -m
      - gunicorn
      - --workers
      - "1"
      - --worker-class
      - sync
      - --timeout
      - "120"
      - --bind
      - 0.0.0.0:8080
      - --name
      - airflow-webserver
      - --access-logfile
      - "-"
      - --error-logfile
      - "-"
      - "airflow.www.app:cached_app()"

  airflow-scheduler:
    build:
      context: ..
      dockerfile: airflow/Dockerfile
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ..:/opt/airflow/project
    command: airflow scheduler

volumes:
  airflow_postgres:
